
name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the version of Node.js that matches Angular requirements

      - name: Install dependencies
        run: npm install --force

      - name: Build Angular project
        run: npm run build -- --output-path=dist  # Customize if your build command or output path differs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Path to the build output
